import type { Metadata, Viewport } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import Nav from "@/components/web/Nav";
import AppShell from "@/components/web/AppShell";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  appleWebApp: {
    capable: true,
    statusBarStyle: "black-translucent"
  },
  manifest: "/manifest.ts",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className="min-h-svh flex flex-col overflow-hidden ">
        <AppShell>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <header className="max-w-2xl w-full mx-auto border-x">
              <Nav />
            </header>
            <main className="px-4 w-full h-full flex-1 overflow-y-auto max-h-[calc(100vh-80px)] no-scrollbar max-w-2xl mx-auto border-x py-4 ">
              {children}
            </main>
          </ThemeProvider>
        </AppShell>
      </body>
    </html>
  );
}
