import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/ui/ThemeProvider";
import Nav from "@/components/web/Nav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl" suppressHydrationWarning>
      <body className="min-h-svh flex flex-col overflow-hidden ">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="max-w-2xl w-full mx-auto border-x">
            <Nav />
          </header>
          <main className="px-4 w-full h-full flex-1 overflow-y-auto max-h-[calc(100vh-80px)] no-scrollbar max-w-2xl mx-auto border-x py-4 ">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
